[package]
name = "monster-deleter-slint"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "monster-deleter"
path = "src/main.rs"

[dependencies]
slint = "1.17.1"
rodio = { version = "0.22.2", default-features = false, features = [
  "playback",
  "mp3",
] }
trash = "5.2.6"
winreg = "0.56.0"
windows-sys = { version = "0.61.2", features = ["Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }


[build-dependencies]
slint-build = "1.17.1"
winres = "0.1.12"


[profile.release]
codegen-units = 1 # 控制代码生成的单元数量
lto = true        # 启用链接时优化, 减少生成的二进制文件的大小并提高性能
opt-level = "s"   # 设置优化级别
panic = "unwind"  # 控制 panic 时的行为 unwind: 在 panic 时展开堆栈
strip = true      # 控制是否剥离生成的二进制文件中的符号信息

[dev-dependencies]
winres = "0.1.12"
